### PR TITLE
Remove defaults and stop outputting fake data

### LINKED ISSUE #87: Stop defaulting values incorrectly
`Cldr::Export::Data::Numbers#unit` uses a default not present in upstream CLDR:

https://github.com/ruby-i18n/ruby-cldr/blob/d180a44bb3533cd173b3282323be0269b6325f74/lib/cldr/export/data/numbers.rb#L108-L114

There are two other places in [`Cldr::Export::Data::Calendars::Gregorian`](https://github.com/ruby-i18n/ruby-cldr/blob/a4834fe8e7d438fb36320ffc41d2f3d646d399a2/lib/cldr/export/data/calendars/gregorian.rb)

### PR DESCRIPTION
**Pull request by movermeyer**
### What are you trying to accomplish?

Fixes #87. Removing defaults that would be incorrect if used.

### What approach did you choose and why?

These commits remove unnecessary defaults. There are no instances of these attributes missing in the CLDR data, so there is no impact on the data exported by `ruby-cldr`.
In all but one case, the attributes are already required attributes (in the [`ldml.dtd`](https://github.com/unicode-org/cldr-staging/blob/85fa5bd46a9c83d2d6e10c4cee1f79f5de0838d0/production/common/dtd/ldml.dtd) schema), so there is no way they could be missing.

In the one case where the attribute is not a required attribute (`type` on `dateTimeFormatLength`), it was defaulting to a value that is not valid (`:format`). Once again, there are no current instances of a `dateTimeFormatLength` without a `type` attribute. In the rare case there were to ever be one, I'd rather have the export fail than silently pass with an invalid default value.

There are two instances in `root` where `<alias>` nodes were being handled incorrectly. Those keys are removed from the output by this change. See [this comment](https://github.com/ruby-i18n/ruby-cldr/pull/88/files#r749563222) for explanation.

### What should reviewers focus on?

🤷

Note that this doesn't solve the problem of mixing number systems (#89).

### The impact of these changes

* Gets rid of defaults that would be dangerous if they were used.
* Gets rid two incorrect data from `root` as a result of not following aliases.

### Testing

You could run `thor cldr:export` for `master` and this branch, then run `diff -r` to compare the outputs:

```bash
git checkout master
thor cldr:export --target=./data_from_master

git checkout movermeyer:mo.stop_outputting_fake_data
thor cldr:export --target=./data_from_pr

diff -r data_from_master data_from_pr
```

Which outputs:

```diff
diff -r data_from_master/root/calendars.yml data_from_pr/root/calendars.yml
81,84d80
<         name:
<           0: ''
<         narrow:
<           0: ''
```

### CODE REVIEW

File: lib/cldr/export/data/calendars/gregorian.rb [hunk 1]
```diff
@@ -92,7 +92,10 @@ def eras
                 path = "#{base_path}/#{name}/*"
                 key  = name.gsub('era', '').gsub(/s$/, '').downcase.to_sym
                 result[key] = select(path).inject({}) do |ret, node|
-                  type = node.attribute('type').value.to_i rescue 0
+                  # TODO: Actually resolve alias nodes
+                  # https://github.com/ruby-i18n/ruby-cldr/issues/78
+                  next {} if node.name == "alias"
```
Comment (movermeyer) [inline lib/cldr/export/data/calendars/gregorian.rb:97]: The `root` locale contains `<alias>` nodes for calendar eras:

* [`dates/calendars/calendar[8]/eras/eraNames/*`](https://github.com/unicode-org/cldr-staging/blob/f20483bff67e44a1326129d59563a52657b0bb04/production/common/main/root.xml#L1264-L1266)
* [`dates/calendars/calendar[8]/eras/eraNarrow/*`](https://github.com/unicode-org/cldr-staging/blob/f20483bff67e44a1326129d59563a52657b0bb04/production/common/main/root.xml#L1271-L1273)

These are incorrectly getting output as:

```yaml
eras:
  abbr:
    0: BCE
    1: CE
  name:
    0: ''
  narrow:
    0: ''
```

Until #78 is addressed, I figure it is better not to output any data, rather than incorrect data.

File: lib/cldr/export/data/calendars/gregorian.rb [hunk 2]
```diff
@@ -91,11 +91,13 @@ def eras
               keys.inject({}) do |result, name|
                 path = "#{base_path}/#{name}/*"
                 key  = name.gsub('era', '').gsub(/s$/, '').downcase.to_sym
-                result[key] = select(path).inject({}) do |ret, node|
-                  type = node.attribute('type').value.to_i rescue 0
+                key_result = select(path).inject({}) do |ret, node|
+                  next ret if node.name == "alias" # TODO: Actually handle alias nodes, https://github.com/ruby-i18n/ruby-cldr/issues/78
```
Comment (movermeyer) [inline lib/cldr/export/data/calendars/gregorian.rb:95]: The `root` locale contains `<alias>` nodes for calendar eras:

* [`dates/calendars/calendar[8]/eras/eraNames/*`](https://github.com/unicode-org/cldr-staging/blob/f20483bff67e44a1326129d59563a52657b0bb04/production/common/main/root.xml#L1264-L1266)
* [`dates/calendars/calendar[8]/eras/eraNarrow/*`](https://github.com/unicode-org/cldr-staging/blob/f20483bff67e44a1326129d59563a52657b0bb04/production/common/main/root.xml#L1271-L1273)

These are incorrectly getting output as:

```yaml
eras:
  abbr:
    0: BCE
    1: CE
  name:
    0: ''
  narrow:
    0: ''
```

Until #78 is addressed, I figure it is better not to output any data, rather than output incorrect data.

**Review by Korri — APPROVED** [review]
